<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    
  </ItemGroup>

<ItemGroup></ItemGroup><ItemGroup></ItemGroup><ItemGroup><Compile Include="T43A\Busqueda.fs" /><Compile Include="T43A\NReinas.fs" /><Compile Include="T43A\CSP.fs" /><Compile Include="T43A\Puzzle8.fs" /><Compile Include="T43A\Program.fs" /><Compile Include="T43A\Pila.fs" /><Compile Include="T43A\Greedy.fs" /><Compile Include="T43A\DFSL.fs" /><Compile Include="T43A\DFS.fs" /><Compile Include="T43A\CostoUniforme.fs" /><Compile Include="T43A\Cola.fs" /><Compile Include="T43A\BFS.fs" /><Compile Include="T43A\AStar.fs" /></ItemGroup></Project>
